version: '3'

services:
  ihm:
    container_name: ihm
    image: pljarlegan/marvel-apollo-demo:1.0.0
    restart: always
    ports:
      - 8080:80
    environment:
      - GRAPHQL_ENDPOINT=http://127.0.0.1:4000
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    stop_grace_period: 1s

